'use client'

import { useEffect, useState } from 'react'
import { ArrowUpRight, Camera, Mail, Menu, MessageCircle, Play, X } from 'lucide-react'
import { CertificateCard, GalleryImage, VideoPlayer } from '@/src/components/media'
import { isPlaceholder, profile, t, whatsappUrl, type CertificateItem, type Language } from '@/src/data/profile'

export default function Page() {
  const [language, setLanguage] = useState<Language>('en')
  const [menuOpen, setMenuOpen] = useState(false)
  const [lightbox, setLightbox] = useState<{ src: string; alt: string } | null>(null)
  const [profileImageAvailable, setProfileImageAvailable] = useState(true)
  const [galleryAvailability, setGalleryAvailability] = useState<Record<string, boolean>>({})
  const isArabic = language === 'ar'
  const text = (value: { en: string; ar: string }) => t(value, language)
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = isArabic ? 'rtl' : 'ltr' }, [language, isArabic])
  const instagram = profile.contact.instagram
  const email = profile.contact.email
  const whatsapp = profile.contact.whatsapp

  return <div className="site-shell">
    <header className="site-header"><a href="#home" className="brand"><span className="brand-mark"><img src="/images/profile.png" alt="Baker Jemai" /></span><span><strong>{text(profile.name)}</strong><small>{isArabic ? 'حافظ وقارئ قرآن' : 'Hafiz · Reciter · Imam'}</small></span></a><button type="button" className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={isArabic ? 'فتح القائمة' : 'Open menu'} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'} aria-label={isArabic ? 'التنقل الرئيسي' : 'Main navigation'}>{profile.navigation.map(item => <a key={item.id} href={`#${item.id}`} onClick={() => setMenuOpen(false)}>{text(item.label)}</a>)}<div className="language-switcher" aria-label={isArabic ? 'اختيار اللغة' : 'Language selection'}><button type="button" className={language === 'en' ? 'active' : ''} aria-pressed={language === 'en'} onClick={() => setLanguage('en')}>EN</button><span aria-hidden="true">|</span><button type="button" className={language === 'ar' ? 'active' : ''} aria-pressed={language === 'ar'} onClick={() => setLanguage('ar')}>العربية</button></div></nav></header>
    <main>
      <section id="home" className="hero section-frame"><div className="hero-copy"><p className="eyebrow">{text(profile.location)} <span className="dot" /> {isArabic ? 'القرآن الكريم' : 'The Holy Quran'}</p><h1>{text(profile.name)}</h1><p className="hero-title">{text(profile.title)}</p><p className="hero-intro">{text(profile.intro)}</p><div className="hero-actions"><a className="button button-primary" href="#recitation"><Play size={16} />{isArabic ? 'استمع إلى تلاوتي' : 'Listen to My Recitation'}</a><a className="button button-ghost" href="#contact">{isArabic ? 'تواصل معي' : 'Contact Me'}<ArrowUpRight size={16} /></a></div></div><button type="button" className="portrait-placeholder" onClick={() => profileImageAvailable && setLightbox({ src: profile.gallery[0].src, alt: text(profile.gallery[0].alt) })} aria-label={isArabic ? 'فتح الصورة الشخصية' : 'Open profile image'} disabled={!profileImageAvailable}><GalleryImage src={profile.gallery[0].src} alt={text(profile.gallery[0].alt)} label={isArabic ? 'الصورة الشخصية' : 'Profile image'} available={profile.gallery[0].available} onError={() => setProfileImageAvailable(false)} /></button></section>
      <div className="ribbon"><span>حفظ القرآن الكريم</span><span>•</span><span>Quran memorization</span><span>•</span><span>إمامة التراويح والتهجد</span></div>
      <section id="about" className="section-frame two-column"><div><p className="section-kicker">01 / {isArabic ? 'من أنا' : 'About'}</p><h2>{isArabic ? 'حياة في خدمة كتاب الله' : 'A Life Dedicated to the Quran'}</h2></div><div className="prose"><p>{text(profile.bio)}</p><div className="fact-list"><div><strong>01</strong><span>{isArabic ? 'حافظ للقرآن الكريم' : 'Hafiz of the Holy Quran'}</span></div><div><strong>02</strong><span>{isArabic ? 'قارئ قرآن وإمام' : 'Quran reciter & Imam'}</span></div><div><strong>03</strong><span>{isArabic ? 'معلّم للقرآن في تونس' : 'Quran teacher in Tunisia'}</span></div></div></div></section>
      <section id="recitation" className="dark-section"><div className="section-frame"><div className="section-heading"><div><p className="section-kicker">02 / {isArabic ? 'التلاوة' : 'Recitation'}</p><h2>{isArabic ? 'تلاوة القرآن الكريم' : 'Quran Recitation'}</h2></div><p>{isArabic ? 'نماذج مختارة من التلاوة' : 'Selected recitations'}</p></div><div className="media-grid">{profile.recitations.map(item => <article className="media-card" key={item.id}><VideoPlayer item={item} language={language} /><div className="media-copy"><p className="eyebrow">{item.achievement ? (isArabic ? 'إنجاز' : 'Achievement') : (isArabic ? 'تلاوة مختارة' : 'Selected recitation')}</p><h3>{text(item.title)}</h3>{item.achievement && <p className="achievement">{text(item.achievement)}</p>}<p className="muted">{text(item.description)}</p></div></article>)}</div></div></section>
      <section id="imamat" className="section-frame split-feature"><div><p className="section-kicker">03 / {isArabic ? 'الإمامة' : 'Imamat'}</p><h2>{isArabic ? 'التراويح والتهجد' : 'Taraweeh & Tahajjud'}</h2><p className="lead">{isArabic ? 'خبرة في خدمة المصلين بخشوع وطمأنينة.' : 'Serving congregations with presence, care, and serenity.'}</p></div><div className="experience-panel"><div className="large-stat">8<span>+</span></div><p>{text(profile.imamat.taraweeh)}</p><div className="rule" /><p>{text(profile.imamat.tahajjud)}</p></div></section>
      <section id="teaching" className="pale-section"><div className="section-frame"><div className="section-heading"><div><p className="section-kicker">04 / {isArabic ? 'التعليم' : 'Teaching'}</p><h2>{isArabic ? 'تعليم القرآن الكريم' : 'Teaching the Quran'}</h2></div><p>{isArabic ? 'مراحل عمرية مختلفة، وهدف واحد: صلة أعمق بالقرآن.' : 'Different ages, one purpose: a deeper connection to the Quran.'}</p></div><div className="teaching-grid">{profile.teaching.map(item => <div className="teaching-card" key={item.id}><span className="age">{text(item.age)}</span><h3>{text(item.title)}</h3><p>{text(item.description)}</p></div>)}</div></div></section>
      <section id="achievements" className="section-frame achievements-section"><div className="section-heading"><div><p className="section-kicker">05 / {isArabic ? 'الإنجازات' : 'Achievements'}</p><h2>{isArabic ? 'المسابقات والإنجازات' : 'Competitions & Achievements'}</h2></div></div><div className="achievement-row">{profile.achievements.map((item, index) => <div className="achievement-highlight" key={item.id}><span className="medal">{item.result.en.startsWith('1st') ? '01' : item.result.en.startsWith('4th') ? '04' : String(index + 1).padStart(2, '0')}</span><div><p className="eyebrow">{text(item.result)}</p><h3>{text(item.title)}</h3><p>{text(item.description)}</p></div></div>)}</div></section>
      <section id="media" className="dark-section media-band"><div className="section-frame"><div className="section-heading"><div><p className="section-kicker">06 / {isArabic ? 'الوسائط' : 'Media'}</p><h2>{isArabic ? 'الوسائط والمعرض' : 'Media & Gallery'}</h2></div>{isPlaceholder(instagram) ? <span className="button button-outline" aria-disabled="true"><Camera size={16} />{isArabic ? 'يُضاف الرابط لاحقًا' : 'Instagram link to be added'}</span> : <a className="button button-outline" href={instagram} target="_blank" rel="noopener noreferrer"><Camera size={16} />{isArabic ? 'زيارة إنستغرام' : 'Visit Instagram'}</a>}</div><div className="gallery-grid">{profile.gallery.map(item => <button type="button" className="gallery-card" key={item.id} disabled={galleryAvailability[item.id] === false} onClick={() => galleryAvailability[item.id] !== false && setLightbox({ src: item.src, alt: text(item.alt) })}><GalleryImage src={item.src} alt={text(item.alt)} label={text(item.category)} available={item.available} onError={() => setGalleryAvailability(current => ({ ...current, [item.id]: false }))} /><span className="gallery-meta"><strong>{text(item.category)}</strong><small>{text(item.alt)}</small></span></button>)}</div><div className="certificates-heading"><p className="section-kicker">{isArabic ? 'الشهادات والتكريمات' : 'Certificates & Recognition'}</p></div><div className="certificate-grid">{profile.certificates.length ? (profile.certificates as readonly CertificateItem[]).map(item => <CertificateCard key={item.id} item={item} language={language} onOpen={(src, alt) => setLightbox({ src, alt })} />) : <div className="empty-media" role="status">{isArabic ? 'تُضاف الشهادات والتكريمات لاحقًا' : 'Certificates and recognition will be added here.'}</div>}</div></div></section>
      <section id="contact" className="contact-section"><div className="section-frame contact-inner"><div><p className="section-kicker">07 / {isArabic ? 'التواصل' : 'Contact'}</p><h2>{isArabic ? 'تواصلوا معي بخصوص برامج رمضان أو الأنشطة القرآنية' : 'Invite Me for Ramadan or Quranic Programs'}</h2><p className="lead">{text(profile.contactMessage)}</p></div><div className="contact-actions">{isPlaceholder(email) ? <span className="contact-link" aria-disabled="true"><Mail size={18} />{isArabic ? 'يُضاف البريد لاحقًا' : 'Email to be added'}</span> : <a href={`mailto:${email}`} className="contact-link"><Mail size={18} />{isArabic ? 'مراسلتي عبر البريد' : 'Email Me'}<ArrowUpRight size={15} /></a>}{isPlaceholder(whatsapp) ? <span className="contact-link" aria-disabled="true"><MessageCircle size={18} />{isArabic ? 'يُضاف واتساب لاحقًا' : 'WhatsApp to be added'}</span> : <a href={whatsappUrl(whatsapp)} className="contact-link" target="_blank" rel="noopener noreferrer"><MessageCircle size={18} />{isArabic ? 'واتساب' : 'WhatsApp'}<ArrowUpRight size={15} /></a>}{isPlaceholder(instagram) ? <span className="contact-link" aria-disabled="true"><Camera size={18} />{isArabic ? 'يُضاف إنستغرام لاحقًا' : 'Instagram to be added'}</span> : <a href={instagram} className="contact-link" target="_blank" rel="noopener noreferrer"><Camera size={18} />Instagram<ArrowUpRight size={15} /></a>}</div></div></section>
      <section className="cta-section"><div className="section-frame cta-inner"><p className="eyebrow">{isArabic ? 'للمساجد والمؤسسات الإسلامية' : 'For mosques & Islamic organizations'}</p><h2>{isArabic ? 'هل تبحثون عن قارئ ضيف لإمامة التراويح في رمضان؟' : 'Looking for a Guest Qari for Ramadan?'}</h2><a className="button button-primary" href="#contact">{isArabic ? 'تواصل معي' : 'Get in Touch'}<ArrowUpRight size={16} /></a></div></section>
    </main>
    <footer className="site-footer"><div><strong>{text(profile.name)}</strong><p>{text(profile.title)}</p></div><div className="footer-meta"><span>© 2026 Baker Jemai</span><button type="button" onClick={() => setLanguage(language === 'en' ? 'ar' : 'en')}>{language === 'en' ? 'العربية' : 'English'}</button></div></footer>
    {lightbox && <button type="button" className="lightbox" onClick={() => setLightbox(null)} aria-label={isArabic ? 'إغلاق الوسائط' : 'Close media'}><img src={lightbox.src} alt={lightbox.alt} onError={() => setLightbox(null)} /><X /></button>}
  </div>
}
